# #*#*#*#*#*#*#*#*#*#*#*#*#*#* AvTimeCases.py *#*#*#*#*#*#*#*#*#*#*#*#*#*# (C) 2026 DekTec
#
# CDTAPI - Writes AvTimeCases.inc: the media clock formulas in arbitrary precision
#
# SPDX-License-Identifier: BSD-3-Clause
#
# The media clock formulas, evaluated with Python's integers, which have no width, for
# fixed and seeded random inputs. TestAvTime.c holds the library's 128-bit arithmetic to
# the values. Run it with Python 3 and commit the result.

import os
import random

NS = 10**9
R32 = 1 << 32
M64 = (1 << 64) - 1
random.seed(2110)


def muladddiv(a, b, add, div):
    return ((a * b + add) // div) & M64


def to_grid(ns, num, den):
    n = (ns * num + den * NS // 2) // (den * NS)
    return ((n * NS * den + num // 2) // num) & M64


def tod2rtp(f, ns):
    frac = 8 if f == 90000 else 2
    return ((ns * f + NS // frac) // NS) & (R32 - 1)


def rtp2tod(f, rtp, approx):
    wraps = approx * f // (R32 * NS)
    diff = rtp - tod2rtp(f, approx)
    if abs(diff) >= R32 // 2:
        wraps += 1 if diff < 0 else -1
    wraps = max(wraps, 0)
    return (((wraps * R32) + rtp) * NS // f) & M64


out = []
out.append('// MulAddDiv: A, B, Add, Div, expected')
out.append('static const uint64_t MulAddDivCases[][5] = {')
cases = [(0, 0, 0, 1), (M64, M64, 0, M64), (M64, M64, M64, 1 << 63), (M64, 2, 0, 3),
         (1 << 63, 1 << 63, 12345, (1 << 62) + 7), (123456789, 987654321, 5, 3)]
for _ in range(14):
    a = random.getrandbits(64)
    b = random.getrandbits(random.choice([8, 20, 40, 64]))
    div = random.getrandbits(random.choice([10, 33, 50, 64])) | 1
    add = random.getrandbits(64) % div
    cases.append((a, b, add, div))
for a, b, add, div in cases:
    out.append('    {UINT64_C(0x%016X), UINT64_C(0x%016X),' % (a, b))
    out.append('     UINT64_C(0x%016X),' % add)
    expected = muladddiv(a, b, add, div)
    out.append('     UINT64_C(0x%016X), UINT64_C(0x%016X)},' % (div, expected))
out.append('};')

tods = [0, 1, 999999999, 1800000000 * NS + 123456789, (R32 - 1) * NS + 999999999,
        1726570000 * NS + 20020000, 4102444800 * NS + 1]
for _ in range(6):
    tods.append(random.randrange(1500000000 * NS, 4290000000 * NS))
rates = [(50, 1), (60000, 1001), (30000, 1001), (24000, 1001), (25, 1), (48000, 1),
         (96000, 1), (44100, 1), (120000, 1001)]

out.append('// ToGrid: Ns, Numerator, Denominator, expected')
out.append('static const uint64_t ToGridCases[][4] = {')
for t in tods:
    for num, den in rates:
        out.append('    {UINT64_C(%d), %d, %d,' % (t, num, den))
        out.append('     UINT64_C(%d)},' % to_grid(t, num, den))
out.append('};')

out.append('// Tod2Rtp: Rate, Ns, expected')
out.append('static const uint64_t Tod2RtpCases[][3] = {')
for t in tods:
    for f in (90000, 48000, 96000, 44100):
        out.append('    {%d, UINT64_C(%d), UINT64_C(%d)},' % (f, t, tod2rtp(f, t)))
out.append('};')

out.append('// Rtp2Tod: Rate, Rtp, ApproxNs, expected')
out.append('static const uint64_t Rtp2TodCases[][4] = {')
for t in tods:
    for f in (90000, 48000, 96000):
        base = tod2rtp(f, t)
        for delta in (0, 1, -1, 1000, -1000, R32 // 2 - 1, -(R32 // 2) + 1, R32 // 2,
                      -(R32 // 2)):
            rtp = (base + delta) % R32
            out.append('    {%d, UINT64_C(%d), UINT64_C(%d),' % (f, rtp, t))
            out.append('     UINT64_C(%d)},' % rtp2tod(f, rtp, t))
out.append('};')

open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'AvTimeCases.inc'),
     'w', encoding='utf-8', newline='\n').write(
    '// Generated by a Python script from the media clock formulas in arbitrary\n'
    '// precision; the reference values of TestAvTime.c.\n\n'
    + '\n'.join(out) + '\n')
