// #*#*#*#*#*#*#*#*#*#*#*#*#*#* TestResult.c *#*#*#*#*#*#*#*#*#*#*#*#*#*#* (C) 2026 DekTec
//
// CDTAPI - Unit tests for the names of result codes
//
// SPDX-License-Identifier: BSD-3-Clause
//
// ResultCodes.inc is generated by CMake from cdtapi_constants.h, one R(Macro) per
// result code, so that a code added to the public header without a name, or with a
// name that differs from its macro, fails here.

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- Include files -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.

// Standard includes
#include <string.h>

// CDTAPI includes
#include "DtTest.h" // Test framework.
#include "cdtapi.h" // Public API under test.

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Every code +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

typedef struct HeaderCode
{
    DtapiResult Code;
    const char* Macro;
} HeaderCode;

static const HeaderCode g_HeaderCodes[] = {
#define R(Macro) {Macro, #Macro},
#include "ResultCodes.inc"
#undef R
};

// The name the library gives a code defined in the public header under Macro.
static const char* ExpectedName(const char* Macro)
{
    if (strcmp(Macro, "DTAPI_E_NO_TS_OUTPUT") == 0)
        return "DTAPI_E_NO_DT_OUTPUT";
    if (strcmp(Macro, "DTAPI_E_NO_TS_INPUT") == 0)
        return "DTAPI_E_NO_DT_INPUT";
    if (strcmp(Macro, "DTAPI_E_INVALID_NUM_INPUTS") == 0 ||
        strcmp(Macro, "DTAPI_E_DISABLED") == 0 || strcmp(Macro, "DTAPI_E_EXCEPTION") == 0)
    {
        return "???";
    }
    return Macro;
}

DT_TEST(EveryHeaderCodeHasItsName)
{
    // Sanity: the generated list really holds the header's codes.
    DT_ASSERT(sizeof(g_HeaderCodes) / sizeof(g_HeaderCodes[0]) > 290);

    for (size_t i = 0; i < sizeof(g_HeaderCodes) / sizeof(g_HeaderCodes[0]); i++)
    {
        const char* Name = DtapiResult2Str(g_HeaderCodes[i].Code);
        const char* Expected = ExpectedName(g_HeaderCodes[i].Macro);

        if (strcmp(Name, Expected) != 0)
            DT_FAIL("%s: expected \"%s\", got \"%s\"", g_HeaderCodes[i].Macro, Expected,
                    Name);
    }
}

DT_TEST(OtherValuesAreUnknown)
{
    DT_ASSERT_STR(DtapiResult2Str(7), "???");
    DT_ASSERT_STR(DtapiResult2Str(DTAPI_E + 10), "???");
    DT_ASSERT_STR(DtapiResult2Str(0xFFFFFFFFU), "???");
    DT_ASSERT_STR(DtapiResult2Str(DTAPI_OK), "DTAPI_OK");
    DT_ASSERT_STR(DtapiResult2Str(DTAPI_E), "DTAPI_E_ATTACHED");
}

DT_TEST_MAIN("Result", DT_RUN(EveryHeaderCodeHasItsName), DT_RUN(OtherValuesAreUnknown))
