// #*#*#*#*#*#*#*#*#*#*#*#*# TestExampleNames.c *#*#*#*#*#*#*#*#*#*#*#*#*# (C) 2026 DekTec
//
// CDtapiLite - Unit tests for the names the example programs give video standards
//
// SPDX-License-Identifier: BSD-3-Clause
//
// VidStdCodes.inc is generated by CMake from CDtapiLite_Constants.h, one V(Macro) per
// DTAPI_VIDSTD_ macro, so that a video standard added to the public header without a name
// in the examples fails here.

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- Include files -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.

// Standard includes
#include <string.h>

// CDtapiLite includes
#include "Common/ExampleCommon.h" // Functions under test.
#include "DtTest.h"               // Test framework.

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Standards +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

typedef struct HeaderVidStd
{
    int VidStd;
    const char* Macro;
} HeaderVidStd;

static const HeaderVidStd g_HeaderVidStds[] = {
#define V(Macro) {Macro, #Macro},
#include "VidStdCodes.inc"
#undef V
};

#define HEADER_COUNT (sizeof(g_HeaderVidStds) / sizeof(g_HeaderVidStds[0]))

// Every standard's name is its macro without DTAPI_VIDSTD_, and gives the standard back,
// in upper and lower case.
DT_TEST(EveryHeaderStandardHasItsName)
{
    size_t i;

    DT_ASSERT_EQ(HEADER_COUNT, 41);

    for (i = 0; i < HEADER_COUNT; i++)
    {
        const char* Expected = g_HeaderVidStds[i].Macro + strlen("DTAPI_VIDSTD_");
        const char* Name = Example_VidStdName(g_HeaderVidStds[i].VidStd);
        char Lower[32];
        int Back = -12345;
        size_t j;

        if (Name == NULL || strcmp(Name, Expected) != 0)
            DT_FAIL("%s is named \"%s\"", g_HeaderVidStds[i].Macro,
                    Name ? Name : "(null)");

        DT_ASSERT(Example_VidStdFromName(Expected, &Back));
        DT_ASSERT_EQ(Back, g_HeaderVidStds[i].VidStd);

        for (j = 0; Expected[j] != '\0' && j + 1 < sizeof(Lower); j++)
            Lower[j] = (char)(Expected[j] >= 'A' && Expected[j] <= 'Z' ? Expected[j] + 32
                                                                       : Expected[j]);
        Lower[j] = '\0';
        Back = -12345;
        DT_ASSERT(Example_VidStdFromName(Lower, &Back));
        DT_ASSERT_EQ(Back, g_HeaderVidStds[i].VidStd);
    }
}

// Numbers and names that are no standard.
DT_TEST(NoStandardHasNoName)
{
    int VidStd = 7;

    DT_ASSERT(Example_VidStdName(12345) == NULL);
    DT_ASSERT(Example_VidStdName(0) == NULL);
    DT_ASSERT(!Example_VidStdFromName("1080I5", &VidStd));
    DT_ASSERT(!Example_VidStdFromName("1080I500", &VidStd));
    DT_ASSERT(!Example_VidStdFromName("", &VidStd));
    DT_ASSERT_EQ(VidStd, 7);
}

// The I/O standards DtapiVidStd2IoStd gives have names.
DT_TEST(IoStandardNames)
{
    DT_ASSERT_STR(Example_IoStdName(DTAPI_IOCONFIG_SDI), "SDI");
    DT_ASSERT_STR(Example_IoStdName(DTAPI_IOCONFIG_HDSDI), "HDSDI");
    DT_ASSERT_STR(Example_IoStdName(DTAPI_IOCONFIG_3GSDI), "3GSDI");
    DT_ASSERT_STR(Example_IoStdName(DTAPI_IOCONFIG_6GSDI), "6GSDI");
    DT_ASSERT_STR(Example_IoStdName(DTAPI_IOCONFIG_12GSDI), "12GSDI");
    DT_ASSERT_STR(Example_IoStdName(DTAPI_IOCONFIG_ASI), "?");
}

DT_TEST_MAIN("ExampleNames", DT_RUN(EveryHeaderStandardHasItsName),
             DT_RUN(NoStandardHasNoName), DT_RUN(IoStandardNames))
