// #*#*#*#*#*#*#*#*#*#*#*#*#*#* TestResult.c *#*#*#*#*#*#*#*#*#*#*#*#*#*#* (C) 2026 DekTec
//
// CDtapiLite - Unit tests for the names of result codes
//
// SPDX-License-Identifier: BSD-3-Clause
//
// ResultCodes.inc is generated by CMake from CDtapiLite_Constants.h, one R(Macro) per
// result code, so that a code added to the public header without a name, or with a
// name that differs from its macro, fails here.

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- Include files -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.

// Standard includes
#include <string.h>

// CDtapiLite includes
#include "CDtapiLite.h" // Public API under test.
#include "DtlTest.h"    // Test framework.

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Every code +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

typedef struct HeaderCode
{
    unsigned int Code;
    const char* Macro;
} HeaderCode;

static const HeaderCode g_HeaderCodes[] = {
#define R(Macro) {Macro, #Macro},
#include "ResultCodes.inc"
#undef R
};

// The name DTAPI gives a code defined in the public header under Macro.
static const char* ExpectedName(const char* Macro)
{
    if (strcmp(Macro, "DTAPI_E_NO_TS_OUTPUT") == 0)
        return "DTAPI_E_NO_DT_OUTPUT";
    if (strcmp(Macro, "DTAPI_E_NO_TS_INPUT") == 0)
        return "DTAPI_E_NO_DT_INPUT";
    if (strcmp(Macro, "DTAPI_E_INVALID_NUM_INPUTS") == 0 ||
        strcmp(Macro, "DTAPI_E_DISABLED") == 0 || strcmp(Macro, "DTAPI_E_EXCEPTION") == 0)
    {
        return "???";
    }
    return Macro;
}

DTL_TEST(EveryHeaderCodeHasItsName)
{
    size_t i;

    // Sanity: the generated list really holds the header's codes.
    DTL_ASSERT(sizeof(g_HeaderCodes) / sizeof(g_HeaderCodes[0]) > 290);

    for (i = 0; i < sizeof(g_HeaderCodes) / sizeof(g_HeaderCodes[0]); i++)
    {
        const char* Name = DtapiResult2Str(g_HeaderCodes[i].Code);
        const char* Expected = ExpectedName(g_HeaderCodes[i].Macro);

        if (strcmp(Name, Expected) != 0)
            DTL_FAIL("%s: expected \"%s\", got \"%s\"", g_HeaderCodes[i].Macro, Expected,
                     Name);
    }
}

DTL_TEST(OtherValuesAreUnknown)
{
    DTL_ASSERT_STR(DtapiResult2Str(7), "???");
    DTL_ASSERT_STR(DtapiResult2Str(DTAPI_E + 10), "???");
    DTL_ASSERT_STR(DtapiResult2Str(0xFFFFFFFFU), "???");
    DTL_ASSERT_STR(DtapiResult2Str(DTAPI_OK), "DTAPI_OK");
    DTL_ASSERT_STR(DtapiResult2Str(DTAPI_E), "DTAPI_E_ATTACHED");
}

DTL_TEST_MAIN("Result", DTL_RUN(EveryHeaderCodeHasItsName),
              DTL_RUN(OtherValuesAreUnknown))
