// #*#*#*#*#*#*#*#*#*#*#*#*#* BenchAvPixConv.c *#*#*#*#*#*#*#*#*#*#*#*#*#* (C) 2026 DekTec
//
// CDTAPI - Measures the throughput of the pixel conversions and of the 4K SDI frame
//
// SPDX-License-Identifier: BSD-3-Clause
//
// Converts a 3840x2160 frame over and over for about a second per conversion, in three
// ways, and prints the compiler and its flags, and for the portable, the SSSE3 and the
// AVX2 conversions the milliseconds a frame takes, where lower is faster, the megabytes
// of input converted per second, where higher is faster, and how many times faster AVX2
// is than SSSE3:
//
//   rows      a row at a time from a frame into a frame, as a transmit FIFO converts
//   packets   a packet's pixel groups at a time from packets with their headers in
//             between into a frame, as a receive FIFO converts
//   cache     one packet over and over into the same memory: the conversion's own speed,
//             without the wait for memory that both others include
//
// It then converts a 2160p frame between the card's coded lines and the raw frame the
// channels carry, both ways, for each standard and symbol size, over as many threads as
// asked for, each taking a band of the lines. Beside the milliseconds it gives the
// millions of cycles a frame where the system says what clock it is running at: that is
// the number which carries to another machine, since a core of half the clock needs
// twice the time for the same cycles. It counts the cycles of the time that passed, not
// those summed over the threads.
//
// The bands run on the same DtWork a channel uses, with a pool that lives for the whole
// run rather than threads started per frame, so what is measured is what a program
// calling the library gets.
//
// Not a test: it asserts nothing about time.
//
// Usage: BenchAvPixConv [seconds per conversion] [threads for the 4K conversion]

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- Include files -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.

// Standard includes
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// CDTAPI includes
#include "AvFifo/DtAvPixConv.h" // Pixel conversions measured.
#include "BenchBuild.h"         // The configuration and flags, generated by CMake.
#include "Core/DtWork.h"        // The bands, over the threads a channel would use.
#include "OAL/OsThread.h"       // The monotonic clock.
#include "Video/DtSdi4k.h"      // The 4K conversions measured.
#include "Video/DtSdiFrame.h"   // The layout they follow.
#include "cdtapi.h"             // DTAPI_VIDSTD_ codes.

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Helpers +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

// Bands of a 4K conversion that can be measured at once.
#define BENCH_MAX_THREADS 32

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- BenchClockGHz -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.
//
// The clock the processor says it is running at, or zero where it does not say. Cycles
// are the time a conversion takes times this clock, and that is the number that carries
// to another machine: divide it by the clock of a core there for the time it would need.
// Neither the nominal clock nor the time-stamp counter serves, since both miss the turbo
// a lightly loaded desktop runs at, which is most of the difference with a server.
//
static double BenchClockGHz(void)
{
#if defined(__linux__)
    FILE* File = fopen("/proc/cpuinfo", "r");
    char Line[256];
    double Highest = 0.0;

    if (File == NULL)
        return 0.0;
    while (fgets(Line, sizeof(Line), File) != NULL)
    {
        double Mhz = 0.0;

        if (sscanf(Line, "cpu MHz : %lf", &Mhz) == 1 && Mhz > Highest)
            Highest = Mhz;
    }
    fclose(File);
    return Highest / 1000.0;
#else
    return 0.0;
#endif
}

#define WIDTH 3840
#define HEIGHT 2160
#define PGROUPS_PER_ROW (WIDTH / 2)
#define FRAME_PGROUPS ((size_t)HEIGHT * PGROUPS_PER_ROW)

// What lies between two packets' pixel groups in a pipe's buffer: the DtEthIp header, 16
// bytes; Ethernet, IPv4, UDP and RTP, 54; the extended sequence number and a row header,
// 8.
#define PACKET_HEADERS 78

// The pixel groups in a packet of the default payload of 1,420 bytes, less the
// extended sequence number and a row header: 282 of 5 bytes, 353 of 4.
#define PACKET_PGROUPS_10 282
#define PACKET_PGROUPS_8 353

typedef enum Which
{
    PG10_TO_UYVY10,
    PG10_TO_UYVY8,
    UYVY10_TO_PG10,
    UYVY8_TO_YUV422P,
    NUM_WHICH
} Which;

static const char* const Names[NUM_WHICH] = {
    "pgroup 10 to UYVY 10", "pgroup 10 to UYVY 8", "UYVY 10 to pgroup 10",
    "UYVY 8 to YUV 4:2:2p"};

typedef enum Way
{
    ROWS,
    PACKETS,
    CACHE,
    NUM_WAYS
} Way;

static const char* const WayNames[NUM_WAYS] = {
    "Rows: a row at a time, from a frame into a frame",
    "Packets: a packet at a time, from packets with headers into a frame",
    "Cache: one packet over and over into the same memory"};

// The memory the conversions read and write.
typedef struct Buffers
{
    uint8_t* Frame;   // The source frame, of 5 bytes per pixel group
    uint8_t* Packets; // The frame's pixel groups in packets, with headers in between
    uint8_t* Dst;     // The destination, of 5 bytes per pixel group
} Buffers;

static int InputBytes(Which Kind)
{
    return Kind == UYVY8_TO_YUV422P ? 4 : 5;
}

// Prints the compiler, its version, the configuration and the flags.
static void PrintCompiler(void)
{
#if defined(__clang__)
    printf("Compiler: Clang %d.%d.%d", __clang_major__, __clang_minor__,
           __clang_patchlevel__);
#elif defined(__GNUC__)
    printf("Compiler: GCC %d.%d.%d", __GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__);
#elif defined(_MSC_VER)
    printf("Compiler: MSVC %d.%d.%d", _MSC_FULL_VER / 10000000,
           _MSC_FULL_VER / 100000 % 100, _MSC_FULL_VER % 100000);
#else
    printf("Compiler: unknown");
#endif
    const char* Flags = BENCH_FLAGS;
    while (*Flags == ' ')
        Flags++;
    printf(", %s, flags \"%s\"\n", BENCH_CONFIG, Flags);
}

// Converts Count pixel groups from Src into pixel group First of a destination of Total
// pixel groups at Dst.
static void Convert(const DtAvPixConv* Conv, Which Kind, const uint8_t* Src, uint8_t* Dst,
                    size_t First, size_t Count, size_t Total)
{
    switch (Kind)
    {
    case PG10_TO_UYVY10:
        Conv->Pg10ToUyvy10(Src, Dst + First * 5, Count);
        break;
    case PG10_TO_UYVY8:
        Conv->Pg10ToUyvy8(Src, Dst + First * 4, Count);
        break;
    case UYVY10_TO_PG10:
        Conv->Uyvy10ToPg10(Src, Dst + First * 5, Count);
        break;
    default:
        Conv->Uyvy8ToYuv422p(Src, Count, Dst + First * 2, Dst + Total * 2 + First,
                             Dst + Total * 3 + First);
        break;
    }
}

// Converts a frame's worth of pixel groups once, in the given way.
static void ConvertFrame(const DtAvPixConv* Conv, Which Kind, Way How, const Buffers* Buf)
{
    size_t Bytes = (size_t)InputBytes(Kind);
    size_t PerPacket = Bytes == 5 ? PACKET_PGROUPS_10 : PACKET_PGROUPS_8;
    if (How == ROWS)
    {
        for (size_t Done = 0; Done < FRAME_PGROUPS; Done += PGROUPS_PER_ROW)
            Convert(Conv, Kind, Buf->Frame + Done * Bytes, Buf->Dst, Done,
                    PGROUPS_PER_ROW, FRAME_PGROUPS);
        return;
    }
    const uint8_t* Src = Buf->Packets + PACKET_HEADERS;
    for (size_t Done = 0; Done < FRAME_PGROUPS; Done += PerPacket)
    {
        size_t Count =
            FRAME_PGROUPS - Done < PerPacket ? FRAME_PGROUPS - Done : PerPacket;
        if (How == PACKETS)
        {
            Convert(Conv, Kind, Src, Buf->Dst, Done, Count, FRAME_PGROUPS);
            Src += Count * Bytes + PACKET_HEADERS;
        }
        else
            Convert(Conv, Kind, Src, Buf->Dst, 0, Count, PerPacket);
    }
}

// The speed of one conversion.
typedef struct Speed
{
    double MsPerFrame;  // Lower is faster
    double MbPerSecond; // Megabytes of input; higher is faster
} Speed;

// Measures one conversion for Seconds.
static Speed Measure(const DtAvPixConv* Conv, Which Kind, Way How, const Buffers* Buf,
                     int Seconds)
{
    size_t Bytes = FRAME_PGROUPS * (size_t)InputBytes(Kind);
    uint64_t Start = OsTime_MonotonicMs();
    uint64_t Elapsed = 0;
    int Frames = 0;
    while (Elapsed < (uint64_t)Seconds * 1000u)
    {
        ConvertFrame(Conv, Kind, How, Buf);
        Frames++;
        Elapsed = OsTime_MonotonicMs() - Start;
    }
    Speed Result;
    Result.MsPerFrame = (double)Elapsed / Frames;
    Result.MbPerSecond =
        (double)Frames * (double)Bytes / 1e6 / ((double)Elapsed / 1000.0);
    return Result;
}

// Lays the frame's pixel groups of Bytes bytes out in packets, headers in between.
static void Packetize(const Buffers* Buf, size_t Bytes)
{
    size_t PerPacket = Bytes == 5 ? PACKET_PGROUPS_10 : PACKET_PGROUPS_8;
    uint8_t* Dst = Buf->Packets;
    for (size_t Done = 0; Done < FRAME_PGROUPS; Done += PerPacket)
    {
        size_t Count =
            FRAME_PGROUPS - Done < PerPacket ? FRAME_PGROUPS - Done : PerPacket;
        memset(Dst, 0, PACKET_HEADERS);
        memcpy(Dst + PACKET_HEADERS, Buf->Frame + Done * Bytes, Count * Bytes);
        Dst += PACKET_HEADERS + Count * Bytes;
    }
}

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+ 4K frames +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
//
// The conversion between the card's coded lines of a 2160p signal over one link and the
// raw frame the channels carry, a line at a time, as DtSdiRx and DtSdiTx do it (0014).
// A card sends 2160p50 and 2160p60 at 12G and 2160p30 at 6G, so the frames a second say
// at once whether one core keeps up.
//

// The stream alignment of a DTA-2178, in bits.
#define SDI_ALIGNMENT 128

typedef struct Sdi4kCase
{
    int VidStd;
    const char* Name;
    const char* Rate;
} Sdi4kCase;

static const Sdi4kCase g_Sdi4kCases[] = {
    {DTAPI_VIDSTD_2160P60, "2160p60", "12G"},
    {DTAPI_VIDSTD_2160P50, "2160p50", "12G"},
    {DTAPI_VIDSTD_2160P30, "2160p30", "6G"},
};

#define NUM_SDI4K_CASES ((int)(sizeof(g_Sdi4kCases) / sizeof(g_Sdi4kCases[0])))

static const int g_Sdi4kBits[] = {10, 16};

#define NUM_SDI4K_SIZES ((int)(sizeof(g_Sdi4kBits) / sizeof(g_Sdi4kBits[0])))

// The memory one case converts.
typedef struct Sdi4kBuffers
{
    uint8_t* Coded;                       // A frame's coded lines, as the ring holds them
    uint8_t* Raw;                         // The raw frame the channels carry
    uint16_t* Scratch[BENCH_MAX_THREADS]; // The working symbols, one set a band
} Sdi4kBuffers;

// What every band of a frame needs. A band takes its own range of lines and its own
// working symbols from the piece number DtWork gives it.
typedef struct Sdi4kJob
{
    const DtSdi4kConv* Conv;
    const DtSdiFrameLayout* Layout;
    int Bits;
    bool ToRaw;
    const Sdi4kBuffers* Buf;
} Sdi4kJob;

// Converts the lines of piece Index of Count, which is what a channel hands to a thread.
static void ConvertBand4k(void* Context, int Index, int Count)
{
    const Sdi4kJob* Job = (const Sdi4kJob*)Context;
    const DtSdiFrameLayout* Layout = Job->Layout;
    size_t RawLine = DtSdiFrame_RawLineBits(Layout, Job->Bits) / 8;
    size_t Coded = 2 * (size_t)Layout->Stride;
    uint16_t* Scratch = Job->Buf->Scratch[Index];
    int First;
    int Last;

    DtWork_Band(Layout->NumLines, Index, Count,
                DtSdiFrame_BandLineStep(Layout, Job->Bits), &First, &Last);
    for (int Line = First; Line < Last; Line++)
    {
        uint8_t* A = Job->Buf->Coded + (size_t)Line * Coded;
        uint8_t* Raw = Job->Buf->Raw + (size_t)Line * RawLine;

        if (Job->ToRaw)
            Job->Conv->ConvertLine(Layout, Job->Bits, A, A + Layout->Stride, Line, Raw,
                                   Scratch);
        else
            Job->Conv->CodeLine(Layout, Job->Bits, Raw, Line, A, A + Layout->Stride,
                                Scratch);
    }
}

// Converts one frame, to the raw frame or back to the coded lines, over the bands the
// DtWork divides it into. This is the mechanism a channel uses, pool and all, so what is
// measured is what a program calling the library gets rather than a copy of it.
static void ConvertFrame4k(const DtSdi4kConv* Conv, const DtSdiFrameLayout* Layout,
                           int Bits, bool ToRaw, const Sdi4kBuffers* Buf,
                           const DtWork* Work)
{
    Sdi4kJob Job;

    Job.Conv = Conv;
    Job.Layout = Layout;
    Job.Bits = Bits;
    Job.ToRaw = ToRaw;
    Job.Buf = Buf;
    DtWork_Run(Work, ConvertBand4k, &Job);
}

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- Measure4k -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.
//
// Measures one conversion for Seconds, in milliseconds a frame and frames a second.
//
static void Measure4k(const DtSdi4kConv* Conv, const DtSdiFrameLayout* Layout, int Bits,
                      bool ToRaw, const Sdi4kBuffers* Buf, int Seconds,
                      const DtWork* Work, double* Ms, double* Fps, double* MCycles)
{
    uint64_t Start = OsTime_MonotonicMs();
    uint64_t Elapsed = 0;
    int Frames = 0;

    while (Elapsed < (uint64_t)Seconds * 1000u)
    {
        ConvertFrame4k(Conv, Layout, Bits, ToRaw, Buf, Work);
        Frames++;
        Elapsed = OsTime_MonotonicMs() - Start;
    }
    *Ms = (double)Elapsed / Frames;
    *Fps = (double)Frames / ((double)Elapsed / 1000.0);
    *MCycles = *Ms * BenchClockGHz(); // Milliseconds times GHz are millions of cycles.
}

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-- Sdi4k -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
//
// Measures every standard and symbol size, both ways, with every conversion the
// processor runs.
//
static void Sdi4k(int Seconds, int Threads)
{
    enum
    {
        NUM_SETS = 2
    };
    static const char* const SetNames[NUM_SETS] = {"C", "SSSE3"};
    const DtSdi4kConv* Sets[NUM_SETS] = {DtSdi4kConv_C(), DtSdi4kConv_Ssse3()};

    // One pool for the whole run, as a channel keeps one between Start and Stop.
    DtWork Work;
    DtWork_Init(&Work);
    if (DtWork_SetThreads(&Work, Threads, "DtBench") != DTAPI_OK)
    {
        printf("Cannot start %d threads\n", Threads);
        return;
    }

    printf("\n4K over one link: the coded lines of the ring and the raw frame, a line at "
           "a time, over %d %s\n",
           Threads, Threads == 1 ? "thread" : "threads");
    if (Sets[1] == NULL)
        printf("This processor or build has no SSSE3\n");
    if (BenchClockGHz() > 0.0)
    {
        printf("At the %.2f GHz this processor reports. The Mcycles are of the time that "
               "passed, not\nsummed over the threads: divide them by the clock of "
               "another core in GHz for the\nmilliseconds the same number of threads "
               "would need there.\n",
               BenchClockGHz());
    }
    else
    {
        printf("This system does not report its clock, so the cycles a frame are left "
               "out and the\nmilliseconds hold for this processor at this speed "
               "alone.\n");
    }
    printf("%-26s %15s %17s %7s\n", "", "ms per frame", "Mcycles a frame", "SSSE3");
    printf("%-28s", "Standard");
    for (int Pass = 0; Pass < 2; Pass++)
    {
        for (int Set = 0; Set < NUM_SETS; Set++)
            printf(" %7s", SetNames[Set]);
    }
    printf(" %7s\n", "vs C");

    for (int c = 0; c < NUM_SDI4K_CASES; c++)
    {
        DtSdiFrameLayout Layout;

        if (!DtSdiFrame_LayoutInit(&Layout, g_Sdi4kCases[c].VidStd, SDI_ALIGNMENT))
            continue;
        for (int s = 0; s < NUM_SDI4K_SIZES; s++)
        {
            int Bits = g_Sdi4kBits[s];
            size_t CodedSize = (size_t)Layout.CodedLines * (size_t)Layout.Stride;
            Sdi4kBuffers Buf;

            bool Short = false;

            Buf.Coded = (uint8_t*)malloc(CodedSize);
            Buf.Raw = (uint8_t*)malloc(DtSdiFrame_RawSize(&Layout, Bits));
            for (int b = 0; b < Threads; b++)
            {
                Buf.Scratch[b] = (uint16_t*)malloc(DtSdiFrame_ScratchSymbols(&Layout) *
                                                   sizeof(uint16_t));
                Short = Short || Buf.Scratch[b] == NULL;
            }
            if (Buf.Coded == NULL || Buf.Raw == NULL || Short)
            {
                printf("Out of memory\n");
                free(Buf.Coded);
                free(Buf.Raw);
                for (int b = 0; b < Threads; b++)
                    free(Buf.Scratch[b]);
                DtWork_Free(&Work);
                return;
            }
            uint32_t State = 2160;
            for (size_t i = 0; i < CodedSize; i++)
            {
                State = State * 1664525u + 1013904223u;
                Buf.Coded[i] = (uint8_t)(State >> 24);
            }
            memset(Buf.Raw, 0, DtSdiFrame_RawSize(&Layout, Bits));

            for (int ToRaw = 1; ToRaw >= 0; ToRaw--)
            {
                double Ms[NUM_SETS] = {0.0, 0.0};
                double Fps[NUM_SETS] = {0.0, 0.0};
                double MCycles[NUM_SETS] = {0.0, 0.0};
                char Name[40];

                snprintf(Name, sizeof(Name), "%s %s %d bits %s", g_Sdi4kCases[c].Name,
                         g_Sdi4kCases[c].Rate, Bits, ToRaw ? "to raw" : "to coded");
                for (int Set = 0; Set < NUM_SETS; Set++)
                {
                    if (Sets[Set] != NULL)
                    {
                        Measure4k(Sets[Set], &Layout, Bits, ToRaw != 0, &Buf, Seconds,
                                  &Work, &Ms[Set], &Fps[Set], &MCycles[Set]);
                    }
                }
                printf("%-28s", Name);
                for (int Set = 0; Set < NUM_SETS; Set++)
                {
                    if (Sets[Set] != NULL)
                        printf(" %7.1f", Ms[Set]);
                    else
                        printf(" %7s", "-");
                }
                for (int Set = 0; Set < NUM_SETS; Set++)
                {
                    if (Sets[Set] == NULL || MCycles[Set] <= 0.0)
                        printf(" %7s", "-");
                    else
                        printf(" %7.1f", MCycles[Set]);
                }
                if (Sets[1] != NULL)
                    printf(" %6.1fx\n", Fps[1] / Fps[0]);
                else
                    printf(" %7s\n", "-");
                fflush(stdout);
            }
            free(Buf.Coded);
            free(Buf.Raw);
            for (int b = 0; b < Threads; b++)
                free(Buf.Scratch[b]);
        }
    }
    DtWork_Free(&Work);
}

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Main +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

int main(int Argc, char** Argv)
{
    int Seconds = Argc > 1 ? atoi(Argv[1]) : 1;
    int Threads = Argc > 2 ? atoi(Argv[2]) : 1;
    size_t Size = FRAME_PGROUPS * 5;
    size_t Packets = FRAME_PGROUPS / PACKET_PGROUPS_10 + 1;
    Buffers Buf;
    Buf.Frame = (uint8_t*)malloc(Size);
    Buf.Packets = (uint8_t*)malloc(Size + Packets * PACKET_HEADERS);
    Buf.Dst = (uint8_t*)malloc(Size);
    if (Buf.Frame == NULL || Buf.Packets == NULL || Buf.Dst == NULL || Seconds <= 0 ||
        Threads < 1 || Threads > BENCH_MAX_THREADS)
    {
        fprintf(stderr,
                "Usage: BenchAvPixConv [seconds per conversion] [threads, 1 to %d]\n",
                BENCH_MAX_THREADS);
        return 1;
    }
    uint32_t State = 2110;
    for (size_t i = 0; i < Size; i++)
    {
        State = State * 1664525u + 1013904223u;
        Buf.Frame[i] = (uint8_t)(State >> 24);
    }

    enum
    {
        NUM_SETS = 3
    };
    static const char* const SetNames[NUM_SETS] = {"C", "SSSE3", "AVX2"};
    const DtAvPixConv* Sets[NUM_SETS] = {DtAvPixConv_C(), DtAvPixConv_Ssse3(),
                                         DtAvPixConv_Avx2()};
    PrintCompiler();
    printf("A 3840x2160 frame; packets of %d pixel groups of 5 bytes or %d of 4 bytes\n",
           PACKET_PGROUPS_10, PACKET_PGROUPS_8);
    if (Sets[1] == NULL || Sets[2] == NULL)
        printf("This processor or build has no %s\n", Sets[1] == NULL ? "SSSE3" : "AVX2");
    for (int How = 0; How < NUM_WAYS; How++)
    {
        printf("\n%s\n", WayNames[How]);
        printf("%-22s %23s %23s %8s\n", "", "ms per frame", "MB of input per s",
               "AVX2 vs");
        printf("%-22s %23s %23s %8s\n", "", "(lower is faster)", "(higher is faster)",
               "SSSE3");
        printf("%-22s", "Conversion");
        for (int Pass = 0; Pass < 2; Pass++)
        {
            for (int Set = 0; Set < NUM_SETS; Set++)
                printf(" %7s", SetNames[Set]);
        }
        printf("\n");
        for (int Kind = 0; Kind < NUM_WHICH; Kind++)
        {
            Packetize(&Buf, (size_t)InputBytes((Which)Kind));
            Speed Speeds[NUM_SETS] = {{0.0, 0.0}, {0.0, 0.0}, {0.0, 0.0}};
            for (int Set = 0; Set < NUM_SETS; Set++)
            {
                if (Sets[Set] != NULL)
                    Speeds[Set] =
                        Measure(Sets[Set], (Which)Kind, (Way)How, &Buf, Seconds);
            }
            printf("%-22s", Names[Kind]);
            for (int Set = 0; Set < NUM_SETS; Set++)
            {
                if (Sets[Set] != NULL)
                    printf(" %7.2f", Speeds[Set].MsPerFrame);
                else
                    printf(" %7s", "-");
            }
            for (int Set = 0; Set < NUM_SETS; Set++)
            {
                if (Sets[Set] != NULL)
                    printf(" %7.0f", Speeds[Set].MbPerSecond);
                else
                    printf(" %7s", "-");
            }
            if (Sets[1] != NULL && Sets[2] != NULL)
                printf(" %7.2fx\n", Speeds[2].MbPerSecond / Speeds[1].MbPerSecond);
            else
                printf(" %8s\n", "-");
        }
    }
    free(Buf.Frame);
    free(Buf.Packets);
    free(Buf.Dst);
    Sdi4k(Seconds, Threads);
    return 0;
}
