// #*#*#*#*#*#*#*#*#*#*#*#*#*#* BenchCommon.h *#*#*#*#*#*#*#*#*#*#*#*#*#*# (C) 2026 DekTec
//
// CDTAPI - What the benchmarks print about the machine and the build
//
// SPDX-License-Identifier: BSD-3-Clause

#pragma once

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- Include files -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.

// Standard includes
#include <stdio.h>

// CDTAPI includes
#include "BenchBuild.h" // The configuration and flags, generated by CMake.

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Machine +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- BenchClockGHz -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.
//
// Returns the clock in GHz that the processor reports it is running at, or zero where it
// does not report one. On Linux, this is the highest "cpu MHz" in /proc/cpuinfo.
//
// The benchmarks multiply a conversion's time by this clock to get its cycles. Cycles
// carry over to another machine. Divide them by the clock of a core there to get the time
// the conversion would take. The nominal clock and the time-stamp counter are not used,
// because both miss the turbo clock of a lightly loaded desktop. That turbo clock is most
// of the difference with a server.
//
static inline double BenchClockGHz(void)
{
#if defined(__linux__)
    FILE* File = fopen("/proc/cpuinfo", "r");
    char Line[256];
    double Highest = 0.0;

    if (File == NULL)
        return 0.0;
    while (fgets(Line, sizeof(Line), File) != NULL)
    {
        double Mhz = 0.0;

        if (sscanf(Line, "cpu MHz : %lf", &Mhz) == 1 && Mhz > Highest)
            Highest = Mhz;
    }
    fclose(File);
    return Highest / 1000.0;
#else
    return 0.0;
#endif
}

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- BenchPrintCompiler -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
//
// Prints the compiler, its version, the configuration and the flags.
//
static inline void BenchPrintCompiler(void)
{
#if defined(__clang__)
    printf("Compiler: Clang %d.%d.%d", __clang_major__, __clang_minor__,
           __clang_patchlevel__);
#elif defined(__GNUC__)
    printf("Compiler: GCC %d.%d.%d", __GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__);
#elif defined(_MSC_VER)
    printf("Compiler: MSVC %d.%d.%d", _MSC_FULL_VER / 10000000,
           _MSC_FULL_VER / 100000 % 100, _MSC_FULL_VER % 100000);
#else
    printf("Compiler: unknown");
#endif
    const char* Flags = BENCH_FLAGS;
    while (*Flags == ' ')
        Flags++;
    printf(", %s, flags \"%s\"\n", BENCH_CONFIG, Flags);
}
