// #*#*#*#*#*#*#*#*#*#*#*#*#* BenchAvPixConv.c *#*#*#*#*#*#*#*#*#*#*#*#*#* (C) 2026 DekTec
//
// CDTAPI - Measures the throughput of each pixel conversion, portable, SSSE3 and AVX2
//
// SPDX-License-Identifier: BSD-3-Clause
//
// Converts a 3840x2160 frame over and over for about a second per conversion, in three
// ways, and prints the compiler and its flags, and for the portable, the SSSE3 and the
// AVX2 conversions the milliseconds a frame takes, where lower is faster, the megabytes
// of input converted per second, where higher is faster, and how many times faster AVX2
// is than SSSE3:
//
//   rows      a row at a time from a frame into a frame, as a transmit FIFO converts
//   packets   a packet's pixel groups at a time from packets with their headers in
//             between into a frame, as a receive FIFO converts
//   cache     one packet over and over into the same memory: the conversion's own speed,
//             without the wait for memory that both others include
//
// Not a test: it asserts nothing about time.
//
// Usage: BenchAvPixConv [seconds per conversion]

// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- Include files -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.

// Standard includes
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// CDTAPI includes
#include "AvFifo/DtAvPixConv.h" // Conversions measured.
#include "BenchBuild.h"         // The configuration and flags, generated by CMake.
#include "OAL/OsThread.h"       // The monotonic clock.

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Helpers +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

#define WIDTH 3840
#define HEIGHT 2160
#define PGROUPS_PER_ROW (WIDTH / 2)
#define FRAME_PGROUPS ((size_t)HEIGHT * PGROUPS_PER_ROW)

// What lies between two packets' pixel groups in a pipe's buffer: the DtEthIp header, 16
// bytes; Ethernet, IPv4, UDP and RTP, 54; the extended sequence number and a row header,
// 8.
#define PACKET_HEADERS 78

// The pixel groups in a packet of DTAPI's default payload of 1,420 bytes, less the
// extended sequence number and a row header: 282 of 5 bytes, 353 of 4.
#define PACKET_PGROUPS_10 282
#define PACKET_PGROUPS_8 353

typedef enum Which
{
    PG10_TO_UYVY10,
    PG10_TO_UYVY8,
    UYVY10_TO_PG10,
    UYVY8_TO_YUV422P,
    NUM_WHICH
} Which;

static const char* const Names[NUM_WHICH] = {
    "pgroup 10 to UYVY 10", "pgroup 10 to UYVY 8", "UYVY 10 to pgroup 10",
    "UYVY 8 to YUV 4:2:2p"};

typedef enum Way
{
    ROWS,
    PACKETS,
    CACHE,
    NUM_WAYS
} Way;

static const char* const WayNames[NUM_WAYS] = {
    "Rows: a row at a time, from a frame into a frame",
    "Packets: a packet at a time, from packets with headers into a frame",
    "Cache: one packet over and over into the same memory"};

// The memory the conversions read and write.
typedef struct Buffers
{
    uint8_t* Frame;   // The source frame, of 5 bytes per pixel group
    uint8_t* Packets; // The frame's pixel groups in packets, with headers in between
    uint8_t* Dst;     // The destination, of 5 bytes per pixel group
} Buffers;

static int InputBytes(Which Kind)
{
    return Kind == UYVY8_TO_YUV422P ? 4 : 5;
}

// Prints the compiler, its version, the configuration and the flags.
static void PrintCompiler(void)
{
#if defined(__clang__)
    printf("Compiler: Clang %d.%d.%d", __clang_major__, __clang_minor__,
           __clang_patchlevel__);
#elif defined(__GNUC__)
    printf("Compiler: GCC %d.%d.%d", __GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__);
#elif defined(_MSC_VER)
    printf("Compiler: MSVC %d.%d.%d", _MSC_FULL_VER / 10000000,
           _MSC_FULL_VER / 100000 % 100, _MSC_FULL_VER % 100000);
#else
    printf("Compiler: unknown");
#endif
    const char* Flags = BENCH_FLAGS;
    while (*Flags == ' ')
        Flags++;
    printf(", %s, flags \"%s\"\n", BENCH_CONFIG, Flags);
}

// Converts Count pixel groups from Src into pixel group First of a destination of Total
// pixel groups at Dst.
static void Convert(const DtAvPixConv* Conv, Which Kind, const uint8_t* Src, uint8_t* Dst,
                    size_t First, size_t Count, size_t Total)
{
    switch (Kind)
    {
    case PG10_TO_UYVY10:
        Conv->Pg10ToUyvy10(Src, Dst + First * 5, Count);
        break;
    case PG10_TO_UYVY8:
        Conv->Pg10ToUyvy8(Src, Dst + First * 4, Count);
        break;
    case UYVY10_TO_PG10:
        Conv->Uyvy10ToPg10(Src, Dst + First * 5, Count);
        break;
    default:
        Conv->Uyvy8ToYuv422p(Src, Count, Dst + First * 2, Dst + Total * 2 + First,
                             Dst + Total * 3 + First);
        break;
    }
}

// Converts a frame's worth of pixel groups once, in the given way.
static void ConvertFrame(const DtAvPixConv* Conv, Which Kind, Way How, const Buffers* Buf)
{
    size_t Bytes = (size_t)InputBytes(Kind);
    size_t PerPacket = Bytes == 5 ? PACKET_PGROUPS_10 : PACKET_PGROUPS_8;
    if (How == ROWS)
    {
        for (size_t Done = 0; Done < FRAME_PGROUPS; Done += PGROUPS_PER_ROW)
            Convert(Conv, Kind, Buf->Frame + Done * Bytes, Buf->Dst, Done,
                    PGROUPS_PER_ROW, FRAME_PGROUPS);
        return;
    }
    const uint8_t* Src = Buf->Packets + PACKET_HEADERS;
    for (size_t Done = 0; Done < FRAME_PGROUPS; Done += PerPacket)
    {
        size_t Count =
            FRAME_PGROUPS - Done < PerPacket ? FRAME_PGROUPS - Done : PerPacket;
        if (How == PACKETS)
        {
            Convert(Conv, Kind, Src, Buf->Dst, Done, Count, FRAME_PGROUPS);
            Src += Count * Bytes + PACKET_HEADERS;
        }
        else
            Convert(Conv, Kind, Src, Buf->Dst, 0, Count, PerPacket);
    }
}

// The speed of one conversion.
typedef struct Speed
{
    double MsPerFrame;  // Lower is faster
    double MbPerSecond; // Megabytes of input; higher is faster
} Speed;

// Measures one conversion for Seconds.
static Speed Measure(const DtAvPixConv* Conv, Which Kind, Way How, const Buffers* Buf,
                     int Seconds)
{
    size_t Bytes = FRAME_PGROUPS * (size_t)InputBytes(Kind);
    uint64_t Start = OsTime_MonotonicMs();
    uint64_t Elapsed = 0;
    int Frames = 0;
    while (Elapsed < (uint64_t)Seconds * 1000u)
    {
        ConvertFrame(Conv, Kind, How, Buf);
        Frames++;
        Elapsed = OsTime_MonotonicMs() - Start;
    }
    Speed Result;
    Result.MsPerFrame = (double)Elapsed / Frames;
    Result.MbPerSecond =
        (double)Frames * (double)Bytes / 1e6 / ((double)Elapsed / 1000.0);
    return Result;
}

// Lays the frame's pixel groups of Bytes bytes out in packets, headers in between.
static void Packetize(const Buffers* Buf, size_t Bytes)
{
    size_t PerPacket = Bytes == 5 ? PACKET_PGROUPS_10 : PACKET_PGROUPS_8;
    uint8_t* Dst = Buf->Packets;
    for (size_t Done = 0; Done < FRAME_PGROUPS; Done += PerPacket)
    {
        size_t Count =
            FRAME_PGROUPS - Done < PerPacket ? FRAME_PGROUPS - Done : PerPacket;
        memset(Dst, 0, PACKET_HEADERS);
        memcpy(Dst + PACKET_HEADERS, Buf->Frame + Done * Bytes, Count * Bytes);
        Dst += PACKET_HEADERS + Count * Bytes;
    }
}

// +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= Main +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

int main(int Argc, char** Argv)
{
    int Seconds = Argc > 1 ? atoi(Argv[1]) : 1;
    size_t Size = FRAME_PGROUPS * 5;
    size_t Packets = FRAME_PGROUPS / PACKET_PGROUPS_10 + 1;
    Buffers Buf;
    Buf.Frame = (uint8_t*)malloc(Size);
    Buf.Packets = (uint8_t*)malloc(Size + Packets * PACKET_HEADERS);
    Buf.Dst = (uint8_t*)malloc(Size);
    if (Buf.Frame == NULL || Buf.Packets == NULL || Buf.Dst == NULL || Seconds <= 0)
    {
        fprintf(stderr, "Usage: BenchAvPixConv [seconds per conversion]\n");
        return 1;
    }
    uint32_t State = 2110;
    for (size_t i = 0; i < Size; i++)
    {
        State = State * 1664525u + 1013904223u;
        Buf.Frame[i] = (uint8_t)(State >> 24);
    }

    enum
    {
        NUM_SETS = 3
    };
    static const char* const SetNames[NUM_SETS] = {"C", "SSSE3", "AVX2"};
    const DtAvPixConv* Sets[NUM_SETS] = {DtAvPixConv_C(), DtAvPixConv_Ssse3(),
                                         DtAvPixConv_Avx2()};
    PrintCompiler();
    printf("A 3840x2160 frame; packets of %d pixel groups of 5 bytes or %d of 4 bytes\n",
           PACKET_PGROUPS_10, PACKET_PGROUPS_8);
    if (Sets[1] == NULL || Sets[2] == NULL)
        printf("This processor or build has no %s\n", Sets[1] == NULL ? "SSSE3" : "AVX2");
    for (int How = 0; How < NUM_WAYS; How++)
    {
        printf("\n%s\n", WayNames[How]);
        printf("%-22s %23s %23s %8s\n", "", "ms per frame", "MB of input per s",
               "AVX2 vs");
        printf("%-22s %23s %23s %8s\n", "", "(lower is faster)", "(higher is faster)",
               "SSSE3");
        printf("%-22s", "Conversion");
        for (int Pass = 0; Pass < 2; Pass++)
        {
            for (int Set = 0; Set < NUM_SETS; Set++)
                printf(" %7s", SetNames[Set]);
        }
        printf("\n");
        for (int Kind = 0; Kind < NUM_WHICH; Kind++)
        {
            Packetize(&Buf, (size_t)InputBytes((Which)Kind));
            Speed Speeds[NUM_SETS] = {{0.0, 0.0}, {0.0, 0.0}, {0.0, 0.0}};
            for (int Set = 0; Set < NUM_SETS; Set++)
            {
                if (Sets[Set] != NULL)
                    Speeds[Set] =
                        Measure(Sets[Set], (Which)Kind, (Way)How, &Buf, Seconds);
            }
            printf("%-22s", Names[Kind]);
            for (int Set = 0; Set < NUM_SETS; Set++)
            {
                if (Sets[Set] != NULL)
                    printf(" %7.2f", Speeds[Set].MsPerFrame);
                else
                    printf(" %7s", "-");
            }
            for (int Set = 0; Set < NUM_SETS; Set++)
            {
                if (Sets[Set] != NULL)
                    printf(" %7.0f", Speeds[Set].MbPerSecond);
                else
                    printf(" %7s", "-");
            }
            if (Sets[1] != NULL && Sets[2] != NULL)
                printf(" %7.2fx\n", Speeds[2].MbPerSecond / Speeds[1].MbPerSecond);
            else
                printf(" %8s\n", "-");
        }
    }
    free(Buf.Frame);
    free(Buf.Packets);
    free(Buf.Dst);
    return 0;
}
